apiVersion: v1
kind: Pod
metadata:
  name: renyi-login
spec:
  containers:
  - name: vol-container
    image: gitlab-registry.nrp-nautilus.io/yol070/research-containers/research-login-v2
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    volumeMounts:
    - name: renyi-volume     #use your own volume path
      mountPath: /renyi-volume
  restartPolicy: Never
  volumes:
    - name: renyi-volume
      persistentVolumeClaim:
        claimName: renyi-volume
