#apiVersion: v1
#kind: Pod
#metadata:
#  name: renyi-gpu-debug
#spec:
#  containers:
#    - name: vol-container
#      image: gitlab-registry.nautilus.optiputer.net/yol070/research-containers/research-login-v2
#      command: [ "sleep", "infinity" ]
#      resources:
#        requests:
#          memory: "8Gi"
#          cpu: "2"
#          nvidia.com/gpu: 1
#          ephemeral-storage: 50Gi
#        limits:
#          memory: "8Gi"
#          cpu: "2"
#          nvidia.com/gpu: 1
#          ephemeral-storage: 50Gi
#      volumeMounts:
#        - name: renyi-volume     #use your own volune path
#          mountPath: /renyi-volume
#  restartPolicy: Never
#  volumes:
#    - name: renyi-volume
#      persistentVolumeClaim:
#        claimName: renyi-volume
#    - name: data
#      emptyDir: { }
#  restartPolicy: Never
#  nodeSelector:
#    gpu-type: "1080Ti"
#    nautilus.io/disktype: nvme

#  GPU Type 	Memory size (GB)
#  1080 	8
#  M4000 	8
#  1080Ti 	11
#  2080Ti 	11
#  TITAN X/XP 	12  4
#  Tesla K40 	12  2
#  Tesla T4 	16  3
#  TITAN RTX 	24  2
#  3090 	24      9
#  Tesla V100 	32  4
#  RTX A100 	40  2
#  RTX8000 	48      0
#  RTX A40 	48      8

# the image will take some hours to be downloaded. pod status will be containercreating
# it will be cached after the first download
apiVersion: v1
kind: Pod
metadata:
  name: renyi-gpu-debug
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: [ "/bin/bash" ]
    args: [ "-c", "sleep infinity" ]
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: 1
      limits:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: 1
    volumeMounts:
    - name: renyi-volume
      mountPath: /renyi-volume

  restartPolicy: Never

  volumes:
    - name: renyi-volume
      persistentVolumeClaim:
        claimName: renyi-volume

  affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: gpu-type
             operator: In
             values:
               - 1080Ti
           - key: topology.kubernetes.io/region
             operator: In
             values:
               - us-west