apiVersion: v1
kind: Pod
metadata:
  name: renyi-debug
spec:
  containers:
  - name: vol-container
    image: gitlab-registry.nautilus.optiputer.net/yol070/research-containers/research-login-v2
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "8Gi"
        cpu: "2"
        nvidia.com/gpu: 1
        ephemeral-storage: 50Gi
      limits:
        memory: "8Gi"
        cpu: "2"
        nvidia.com/gpu: 1
        ephemeral-storage: 50Gi
    volumeMounts:
    - name: renyi-volume     #use your own volune path
      mountPath: /renyi-volume
  restartPolicy: Never
  volumes:
    - name: renyi-volume
      persistentVolumeClaim:
        claimName: renyi-volume
    - name: data
      emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    gpu-type: "1080Ti"
    nautilus.io/disktype: nvme
