apiVersion: batch/v1
kind: Job
metadata:
  name: renyi-cifar100-2
spec:
  template:
    spec:
      containers:
      - name: pytorch-container
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
        workingDir: /renyi-volume/lfmlib/lfm/
        command: ["bash", "train.sh"]
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: renyi-volume
          mountPath: /renyi-volume

      restartPolicy: Never

      volumes:
        - name: renyi-volume
          persistentVolumeClaim:
            claimName: renyi-volume

      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: nvidia.com/gpu.product
                 operator: In
                 values:
                   - NVIDIA-GeForce-GTX-1080-Ti
               - key: topology.kubernetes.io/region
                 operator: In
                 values:
                   - us-west
  backoffLimit: 1